### ISSUE TITLE
Allow spaces in album titles

### ISSUE THREAD

**Issue by bll07** [philbertphotos/Zenphoto-Lightroom-Publisher#11]
Hi,
I usually use spaces in my album titles. That is also necessary as my zenphoto layout is pretty narrow with the album title.
Any chance to get this? The server-side folder does not need spaces, as in zenphoto itself it might use underscores instead of spaces.

Thanks!
Chris

**Comment by philbertphotos** [comment]
I have an updating that is on the way that will allow spaces in album names and automatically use underscores in folder-names

**Comment by bll07** [comment]
Great, thanks!
