### ISSUE TITLE
Cannot sync images

### ISSUE THREAD

**Issue by ghost** [philbertphotos/Zenphoto-Lightroom-Publisher#14]
With version 4.0.1.20130423 sync all images and sync images for a single album do not work (i. e. images do not show up in lightroom). Uploading images does work. But when trying to sync afterwards, the alreday uploaded images are marked as to be deleted with the next publish option. (LR version 4.4, zenphoto version 1.4.4.4).

Any help would be appreciated.
Thanks Ralf

**Comment by philbertphotos** [comment]
this is something I will check out and send a fix tonight ... you are the second person to report this .

**Comment by philbertphotos** [comment]
Can you please send me the log file (in debug mode) please delete and try the sync then send me the log.
Please make sure you remove your password info for the log.

**Comment by philbertphotos** [comment]
Other question OSX or Windows??

**Comment by ghost** [comment]
OS: Win8, Which logfile: The lightroom plugin logfile?

**Comment by philbertphotos** [comment]
Here you go..
![pps-2013-05-01 at 05 53 34](https://f.cloud.github.com/assets/2892474/448429/1a1522be-b245-11e2-97ea-44fdb7d8571e.png)

**Comment by philbertphotos** [comment]
Issued a fixed for the problem
https://github.com/philbertphotos/Zenphoto-Lightroom-Publisher/blob/4.0.1/zp-lightroom/xmlrpc.php

**Comment by philbertphotos** [comment]
I finished the rewrite of the first beta release of version 4.5.0... I
think you will be happy with this one. 

http://philbertphotos.github.io/Zenphoto-Lightroom-Publisher/ 

On 2013-05-01 04:42, Ra10 wrote: 

> OS: Win8, Which logfile: The lightroom plugin logfile? 
> 
> ## 
> 
> Reply to this email directly or view it on GitHub [1].

## 

```
     [2]
```

 Joseph Philbert | Photographer 
 Philbert Photography | Alexandria, Virginia 22311 
 888-596-0392 | 340-244-3867 
 [2] [3] [4] [5] 

## Links:

[1]
https://github.com/philbertphotos/Zenphoto-Lightroom-Publisher/issues/14#issuecomment-17273268
[2] http://www.philbertphotography.com
[3] http://www.companysig.com/vcards/show_vcard2.php/BDMBXH931035.vcf
[4] http://fb.com/philbertphotography
[5] http://www.twitter.com/philbertphotos
