### ISSUE TITLE
“Server could not be connected”

### ISSUE THREAD

**Issue by Bruno21** [philbertphotos/Zenphoto-Lightroom-Publisher#15]
Hi,

I can't login to my zenphoto site from lightroom. Always get the “Server could not be connected” message.

OS: osx 10.8.3
zenphoto 1.4.4.5
LR 4.4
latest zenpublisher 4.0.1.20130423

I will send you the log to your mail.

**Comment by philbertphotos** [comment]
I got the log file and looking into it .. since I have never tried it out were a zenphoto install is in a subfolder I will need to test this to make sure it will work that way and fix it .

**Comment by Bruno21** [comment]
Hello Joseph,

Tried 4.5.0.20130513 BETA

Same “Server could not be connected” message.

Maybe a mistake with this line ["webpath"] = "/plugins/zp-lightroom/";

My zenphoto plugins folder:
/zenphoto/plugins/ZenPublisher/ZenRPC.php
/zenphoto/plugins/ZenPublisher.php

I will send you the log to your mail.

**Comment by philbertphotos** [comment]
Confirmed issues with some servers, reported by a user.

## I actually did a API test directly on your server so I know it works ... Thanks for your help... A fix is available, if you find any other bugs let me know .... 

It seems some hosts will throw a 400 ERROR if you used a different User-Agent so I changed it to make it a bit more like others. Bigger problem was using 'Host' in the header all it has is you own web host but that also cause a issue.. 

This was from the original coder and I dont see the need for it.
