### ISSUE TITLE
Cannot sync sub-albums

### ISSUE THREAD

**Issue by f0b04707** [philbertphotos/Zenphoto-Lightroom-Publisher#17]
- Mac OS X 10.8.3
- Lightroom 4.4
- Zenphoto version 1.4.4.5

After initial setup, "Sync albums" does not retrieve sub-albums.

**Comment by philbertphotos** [comment]
I know about the issue ...but thanks for the log there is a update I am still testing that will fix that and other issues so look for a update in the next few hours I am still going over and looking for new bugs with the changes I made.

I will check the log file to make sure I did not miss anything.

**Comment by f0b04707** [comment]
Last version does not fix the issue unfortunately... Removed completely the plug-in, re-installed it... but the sub-folders are not synchronized at all...

**Comment by philbertphotos** [comment]
I find that strange .. I have to see the logs to make a fix. a folder being a sub folder should have no problem syncing in all the test I have done. I am curious how nested are the subfolders?

**Comment by philbertphotos** [comment]
I issued a small fix for this problem it now find unpublished nested subalbums.
https://github.com/philbertphotos/Zenphoto-Lightroom-Publisher/blob/4.5.0/plugins/ZenPublisher/ZenRPC.php
