### ISSUE TITLE
Sync Albums/Images

### ISSUE THREAD

**Issue by FotoRiC** [philbertphotos/Zenphoto-Lightroom-Publisher#18]
ZenPhoto Publisher allowed the creation of the albums, but did not allow uploads of images. I had to create the albums on ZenPhoto online, then click the Sync Albums/Images to get them into Lightroom.

After creating albums on ZenPhoto, I was able to put photos in the albums and upload all photos to the albums correctly.

After asking ZenPhoto Publisher to Sync Albums/Images, it went through the motions, but left empty albums in Lightroom 4. The images are still on ZenPhoto online.

**Comment by philbertphotos** [comment]
I think this is a MAC issue and I have to do a test on that system to see why it happens. I tested on a PC on lightroom 3 and 4 with no issues making or syncing files.

please send me the log file. If you using build 0520 you can send it from within Lightroom

**Comment by FotoRiC** [comment]
Sorry, I should have said I'm using a PC not a MAC.
I am using 4.5.0.20130513 of the plugin.
The "Save Diagnostic Log to File" button is greyed out.

**Comment by philbertphotos** [comment]
Ok there is a new version on-line 4.5.0.20130520 -- try that one ... I will do a few more tests, but I am thinking it could be a host issue but I will find out. Before you send any logs you need to repeat the problem. If you going to send it outside lightroom please remove any password information in it (simple search and replace) if done with the new version it does that for you.

**Comment by FotoRiC** [comment]
I have installed the new version and the Lightroom albums have now been populated with the images.
Good job.

**Comment by philbertphotos** [comment]
GREAT .... let me know if you get any other issues.
