### ISSUE TITLE
Error while sync all albums

### ISSUE THREAD

**Issue by Cyberdoc** [philbertphotos/Zenphoto-Lightroom-Publisher#3]
I've tried to initially sync all albums (following the description), but I get an error message, after the "Sync albums" button click:

[string "ZenphotoExportServiceProvider.lua"]: 387: bad argument #1 to 'pairs' (table expected, got nil)

LR 4.3
Zenphoto 1.4.4.3

**Comment by philbertphotos** [comment]
I tested this a few days ago and it worked, I will look at it again ..I have a big update coming that adds support for multiple Zenphoto installs.

**Comment by Cyberdoc** [comment]
I am only using one Zenphoto installation. But if you need some other information or logs, tell me, I am glad to help. Because I would be happy if this working as easy, as you have described it!

**Comment by philbertphotos** [comment]
What would really help is if you can reproduce the bug with the "debug log" turned on. It saves the log file in you default my documents folder.

send me that file to "joe@philbertphotos.com"

**Comment by philbertphotos** [comment]
Issue has been corrected, I was able to to reproduce the error..

Thank you for reporting the issue.  please check after you update your version works for you.

**Comment by Cyberdoc** [comment]
Sync of Albums is working now! Perfect!

Sync of Images causes now the next error:
[string "ZenphotoPublishSupportExtension.lua"]: 92: attempt to call global 'warn' (a nil value)

**Comment by philbertphotos** [comment]
Ok fixed it .. should be fine now after you update with the new version..

**Comment by Cyberdoc** [comment]
Yep, is working now. Can sync photos and albums.

One enhancement: When doing the "sync all", the plugin creates an album in the Zenphoto installation (sync-folder), this folder should not be deleted out of Zenphoto (in my case the installation was broken after that, and I had to run the setup again).Via a ftp client you can delete this folder without any problems.
For what reason is this folder needed?

Btw. great job!

**Comment by philbertphotos** [comment]
"sync all" folder is no longer a issue.
