### ISSUE TITLE
plugin error when publishing new photo in collection

### ISSUE THREAD

**Issue by jasonized** [philbertphotos/Zenphoto-Lightroom-Publisher#4]
Greetings Joe!  
##   When I added one image (testing) to a album, I get this error in the logs:

Plug-in error log for plug-in at: /Applications/ZenphotoPublisher3.0.1/zp-publisher.lrplugin

***\* Error 1

This plug-inâ€™s post-processing task did not finish successfully.
## ZenphotoExportServiceProvider.lua:560: attempt to call global 'info' (a nil value)

It's interesting to note: the image was published, but the error occurred when trying to update the collection in LR.  Checking the zenphoto album, the image was posted successfully.  I should note, the HTML upload does not work for me at all, I had to switch to xml before it would update the image.
(I have no idea why the text is bolding/unbolding by itself in this message!)

**Comment by philbertphotos** [comment]
Ok its fixed .. just update and enjoy :)

**Comment by jasonized** [comment]
Wow, that was fast!  Okay, tested, and the update fixed that one.  :}    

I'm glad to see this is being supported again, your support is much appreciated.

Cheers!

Jason
