### ISSUE TITLE
Deleted image from collection deletes, but error message always pops up

### ISSUE THREAD

**Issue by jasonized** [philbertphotos/Zenphoto-Lightroom-Publisher#5]
When you delete an image from a published collection, the image is removed from both the website and the LR published collection, but an error message pops up for every message deleted:

Unable to delete image with id: xxxx
<?xml version="1.0"?>

There is nothing generated in the log file.

(Since I apparently closed the other issue by mistake, I'm opening a new one. Sigh.)

Thanks!

Jason

**Comment by philbertphotos** [comment]
I will look at this and do a few test ... and make an update.

**Comment by jasonized** [comment]
Thanks...  Looks like the only place that message exists is in
ZenphotoPublishSupport.lua...

Cheers!

Jason

**Comment by philbertphotos** [comment]
This has been fixed..
