### ISSUE TITLE
Can not edit individual albums

### ISSUE THREAD

**Issue by jasonized** [philbertphotos/Zenphoto-Lightroom-Publisher#7]
This is on a mac (two different ones).  control/right-click on an album to access edit function causes an error message:

An internal error has occurred.
Invalid parameter not satifsying: aString != nil

There is nothing in the debug log.

Thanks!

jason

**Comment by philbertphotos** [comment]
That will be a tough one since I dont have a mac :( but I will do some research.... btw I will release version 3.0.2 that has several updates and quite a few fixes .. look for it in a few hours. (testing)

**Comment by philbertphotos** [comment]
Do me a favor check the plugin manager to see it there any additional info and save it to a log file (if there are any)and post it here..
![PPS-2013-03-23 at 15 13 31](https://f.cloud.github.com/assets/2892474/294450/e88e578a-93ed-11e2-9b37-58dd3a855716.png)

**Comment by jasonized** [comment]
That's the first thing I did, went in and turned it log-debug, and
repeated the test... nothing in the log to write.

Sigh.

Jason

**Comment by philbertphotos** [comment]
Ok only thing you can do is do a screen shot before, during and after the bug ... that way I can maybe find out what is causing it..

**Comment by jasonized** [comment]
Same thing with the can not create albums problem.. no diags at all in
the logs.   If you have a generic string or something I can put in
various places, I'm willing to give it a try. :}

Screen shot shows nothing other than standard LR, before, and the error
block after.   (Yellow ! lr triangle).

If you think it would help, I can give you a temp login on my system via
VNC and let you try it.

Cheers!

Jason

**Comment by jasonized** [comment]
Found another...  Right-click on album, 'show album on zenphoto'...
fails, missing a '/' between domain and index.php.

i.e, firefox gives an error page with: Firefox can not find the server
at http://www.undescribable.comindex.php.  Server does not exist.

Sadly, this plugin has been neglected for years now...

Cheers!

Jason

**Comment by philbertphotos** [comment]
Yea let me know VNC will help greatly..

**Comment by jasonized** [comment]
I sent you a private email with info...   if you haven't seen it, it's
probably in your spam filter. :}

Cheers!

Jason

**Comment by philbertphotos** [comment]
Check your email it is not working

**Comment by jasonized** [comment]
try again...

**Comment by philbertphotos** [comment]
This has been fixed in the 3.0.2 branch
